- name: this is a play at the top level of a file
  hosts: all
  remote_user: root

  tasks:

  - name: reboot
    command: shutdown -r now 'Rebooting to complete system upgrade'
      removes=/var/run/reboot-required
